### PR TITLE
 Add configurable error_limit option

### PR DESCRIPTION
**Pull request by jasonm23**
- [x] Update README.md
- [x] Whitelist new :error_limit option
- [x] Set default :error_limit to 5
- [x] sends option[:error_limit] instead of hardcoded 5 from dsl
- [x] import result checks for option[:error_limit]

### CODE REVIEW

**Comment by Fivell** [comment]
@jasonm23 , this makes sense, thanks, will review and merge little later

**Comment by jasonm23** [comment]
@Fivell hey Igor, we noticed that this limit must be set very low (depending on the content of errors.) Otherwise there's a cookie overflow - due to the oversized flash message.

I think it'll be worth added some sort of error reporting.

Although at the moment I don't have a time available to do this, I will attempt it at some point if it's not picked up.

**Comment by Fivell** [comment]
@jasonm23 , yes you're right, looks like this works on for active-record based session store.

**Comment by jasonm23** [comment]
Session makes the most sense

**Pull request merged**
